#!/usr/bin/env node
/**
 * Generate a large Netscape bookmark file on demand.
 *
 * Purpose: make the two measurements docs/11 asks for actually runnable — the
 *   10 000-node responsiveness item in §5, and the 100 000-node parse budget in
 *   §6 that has only ever been measured under jsdom.
 * Inputs: a node count and an output path.
 * Guarantees: exactly `--nodes` nodes (folders + bookmarks), valid Netscape
 *   HTML, deterministic for a given seed — so two runs are comparable.
 *
 * docs/11 §2 named a `generate-huge.ts` for this and `.gitignore` has always
 * reserved `tests/fixtures/generated/` for its output, but the script itself was
 * never written, which is why the 2 s budget stayed unmeasured (docs/00 §10.8).
 *
 * Usage:
 *   node scripts/gen-fixture.mjs --nodes 10000 --out tests/fixtures/generated/big.html
 *   node scripts/gen-fixture.mjs --nodes 100000 --per-folder 100 --seed 7 --out …
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/** Mulberry32 — small, seeded, and good enough for shaping test data. */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function parseArgs(argv) {
  const out = { nodes: 10_000, perFolder: 50, seed: 1, out: undefined };
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i];
    const value = argv[i + 1];
    if (key === '--nodes') out.nodes = Number(value);
    else if (key === '--per-folder') out.perFolder = Number(value);
    else if (key === '--seed') out.seed = Number(value);
    else if (key === '--out') out.out = value;
  }
  return out;
}

/**
 * Titles that exercise the escaping path, not just ASCII.
 *
 * A 100k file of `Bookmark 1..n` would measure string concatenation and nothing
 * else; entities, CJK and emoji are what the parser actually spends time on.
 */
const TITLE_POOL = [
  'Example bookmark',
  'Quotes &quot;here&quot;',
  'Ampersand &amp; more',
  'Angle &lt;brackets&gt;',
  'ブックマーク',
  'Thư mục quan trọng',
  '🌸 emoji title',
  'A rather long bookmark title that wraps in most reasonable window widths',
];

function build({ nodes, perFolder, seed }) {
  const rand = rng(seed);
  const lines = [
    '<!DOCTYPE NETSCAPE-Bookmark-file-1>',
    '<!-- Generated by scripts/gen-fixture.mjs — not a real export. -->',
    '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">',
    '<TITLE>Bookmarks</TITLE>',
    '<H1>Bookmarks</H1>',
    '<DL><p>',
  ];

  let written = 0;
  let folderIndex = 0;
  const indent = (depth) => '    '.repeat(depth);

  // Depth 3 so the walk is exercised, but nowhere near the 200 cap — this file
  // is for measuring the common case, not the limit.
  const emitFolder = (depth) => {
    if (written >= nodes) return;
    folderIndex++;
    const stamp = 1700000000 + folderIndex;
    lines.push(
      `${indent(depth)}<DT><H3 ADD_DATE="${stamp}" LAST_MODIFIED="${stamp + 1}"${
        folderIndex === 1 ? ' PERSONAL_TOOLBAR_FOLDER="true"' : ''
      }>Folder ${folderIndex}</H3>`,
      `${indent(depth)}<DL><p>`,
    );
    written++;

    const count = Math.min(perFolder, nodes - written);
    for (let i = 0; i < count; i++) {
      const title = TITLE_POOL[Math.floor(rand() * TITLE_POOL.length)];
      const stampB = 1700000000 + written;
      lines.push(
        `${indent(depth + 1)}<DT><A HREF="https://host${written % 997}.example/p${written}?q=${written}" ` +
          `ADD_DATE="${stampB}">${title}</A>`,
      );
      written++;
    }

    if (depth < 3 && written < nodes) emitFolder(depth + 1);
    lines.push(`${indent(depth)}</DL><p>`);
  };

  while (written < nodes) emitFolder(1);
  lines.push('</DL><p>', '');
  return lines.join('\n');
}

const options = parseArgs(process.argv.slice(2));

if (options.out === undefined || !Number.isFinite(options.nodes) || options.nodes < 1) {
  console.error(
    'usage: node scripts/gen-fixture.mjs --nodes <n> --out <path> [--per-folder <n>] [--seed <n>]',
  );
  process.exitCode = 1;
} else {
  const html = build(options);
  mkdirSync(dirname(options.out), { recursive: true });
  writeFileSync(options.out, html);
  const mb = (Buffer.byteLength(html) / 1024 / 1024).toFixed(1);
  console.error(`wrote ${options.out} — ${options.nodes} nodes, ${mb} MB`);
}
